language: python
sudo: false
python:
  - 2.7
  - 3.5
  - pypy-5.4.1
env:
  matrix:
    - ENV=latest
    - ENV=tx1
script:
  - coverage run `which zope-testrunner` --test-path=src  --auto-color --auto-progress
after_success:
  - coveralls
notifications:
  email: dev-regression-tests@nextthought.com

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"
  - if [[ $ENV == tx1 ]]; then pip install transaction==1.7.0 ZODB==4.4.3; fi

# cache: pip seems not to work if `install` is replaced (https://github.com/travis-ci/travis-ci/issues/3239)
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.venv
    - $HOME/.runtimes
    - $HOME/.wheelhouse

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
